### ISSUE TITLE
BUG: fechas de arribo-vuelta no se graban

### ISSUE THREAD

**Issue by rusonariga** [BuenosCodes/etitango-front#133]
verificar por que nos e graban als fechas en el form, siempre aparecen las mismas para todos.

**Comment by thehighestprimenumber** [comment]
parece que no se está seteando bien en el FE, lo podés revisar @amartinezsaucedo ?
Lo mismo con http://localhost:3000/super-admin/events, cuando modificás solo un valor, se pierden las fechas originales
