### ISSUE TITLE
asistente: subir comprobante de transferencia

### ISSUE THREAD

**Issue by rusonariga** [BuenosCodes/etitango-front#152]
Dentro de la solapa "inscripcion al proximo eti"

- Una vez que uno esta inscripto, el form tiene que quedar deshabilitado.

- Tiene que habilitarse una seccion abajo con un boton que diga "SUBI TU COMPROBANTE DE TRNASFERENCIA"

- emitir un mensaje por pantalla que diga "su comprobante se ha subido satisfactoriamente. Cuando los oranizadores procesn su pago, le llegara una notificacion via mail"

- Cambiar estatus a "en verificacion de pago"

**Comment by amartinezsaucedo** [comment]
Formatos: imágenes o pdf
