### ISSUE TITLE
Primer ingreso post creacion de cuenta / logeo con opciones por primera vez

### ISSUE THREAD

**Issue by rusonariga** [BuenosCodes/etitango-front#40]
Una vez que se crean la cuenta con un mail propio o se logeen por primera vez, los usuarios deben ser dirigidos al form de sus opciones personales, los cuales deben ser completados si o si para que se habiliten el resto de las opciones del dashboard.
del figma, seria el "dashboard_1"

![Image](https://user-images.githubusercontent.com/50117587/181662122-bc14f0e3-e3e4-4289-b2e8-ad2a2b129930.png)

**Comment by thehighestprimenumber** [comment]
@rusonariga creo que esto está hecho, no?

**Comment by rusonariga** [comment]
podriamos decir q la primer parte si, faltaria agregarle la parte del "perfil etiano" que es donde se acceden a los comprobantes subidos con anterioridad y la comida. El rol del baila ya esta incluido en el form actual.

**Comment by thehighestprimenumber** [comment]
qué significa "donde acceden a la comida"?
Porfa creá un ticket aparte para las cosas que faltan así cerramos este.

**Comment by rusonariga** [comment]
done!

**Comment by thehighestprimenumber** [comment]
cuál es el ticket nuevo? linkealo acá así queda registro
